### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by niwinz**

### CODE REVIEW

**Comment by Alotor** [comment]
Awesome :beers:

**Comment by Alotor** [comment]
@niwinz I think you forgot to upload "compiler.jar"

**Comment by niwinz** [comment]
Nice! 

About compiler.jar, I didn't include it explicitly because I don't want include it in the jar. The compile script is just for remember the entire comand line. The compiler is a google closure compiler latest version.

**Comment by niwinz** [comment]
How about new release? I'll need it soon on uxbox :P

**Comment by Alotor** [comment]
Ok. I'm finishing support for CDATA tomorrow I'll try to finish it and
create a release

**Comment by Alotor** [comment]
Released 0.2.0 version :smile:

**Pull request merged**
